services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-filevault_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-filevault_pass}
      POSTGRES_DB: ${POSTGRES_DB:-filevault_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filevault_user -d filevault_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../backend/.env.docker
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app
      - file_storage:/data/files
    command: ["./server"]

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8080

volumes:
  db_data:
  file_storage: