package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/rishit911/file_vault_proj-backend/graph/generated"
	"github.com/rishit911/file_vault_proj-backend/graph/model"
	"github.com/rishit911/file_vault_proj-backend/internal/auth"
	"github.com/rishit911/file_vault_proj-backend/internal/crypto"
	"github.com/rishit911/file_vault_proj-backend/internal/db"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	hashed, err := auth.HashPassword(password)
	if err != nil {
		return nil, err
	}

	id := uuid.New().String()
	_, err = r.DB.Exec(`INSERT INTO users (id, email, password_hash) VALUES ($1,$2,$3)`, id, email, hashed)
	if err != nil {
		return nil, err
	}

	token, err := auth.GenerateJWT(id, 24*time.Hour)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        id,
			Email:     email,
			Role:      "user",
			CreatedAt: time.Now(),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	var id, pwHash string
	if err := r.DB.QueryRowx(`SELECT id, password_hash FROM users WHERE email=$1`, email).Scan(&id, &pwHash); err != nil {
		return nil, err
	}

	if err := auth.CompareHashAndPassword(pwHash, password); err != nil {
		return nil, err
	}

	token, err := auth.GenerateJWT(id, 24*time.Hour)
	if err != nil {
		return nil, err
	}

	var createdAt time.Time
	_ = r.DB.Get(&createdAt, "SELECT created_at FROM users WHERE id=$1", id)

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        id,
			Email:     email,
			Role:      "user",
			CreatedAt: createdAt,
		},
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, userFileID string) (*model.DeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// CreateShare is the resolver for the createShare field.
func (r *mutationResolver) CreateShare(ctx context.Context, input model.ShareCreateInput) (*model.ShareCreatePayload, error) {
	userID, _ := ctx.Value("userID").(string)
	if userID == "" {
		return nil, fmt.Errorf("unauthenticated")
	}

	// validate ownership if fileId provided
	if input.FileID != nil {
		ownerID, err := db.GetFileOwnerID(ctx, r.DB.DB, *input.FileID)
		if err != nil {
			return nil, err
		}
		if ownerID != userID {
			return nil, fmt.Errorf("only uploader can share")
		}
	}

	// generate token
	token, err := crypto.GenerateShareToken(18)
	if err != nil {
		return nil, err
	}

	publicVal := true
	if input.Public != nil {
		publicVal = *input.Public
	}

	share := db.Share{
		FileID:       input.FileID,
		FolderID:     input.FolderID,
		OwnerID:      userID,
		Token:        token,
		Public:       publicVal,
		ExpiresAt:    input.ExpiresAt,
		MaxDownloads: input.MaxDownloads,
	}

	created, err := db.CreateShare(ctx, r.DB.DB, share)
	if err != nil {
		return nil, err
	}

	baseURL := os.Getenv("BASE_URL")
	if baseURL == "" {
		baseURL = "http://localhost:8080"
	}
	url := strings.TrimRight(baseURL, "/") + "/s/" + created.Token

	return &model.ShareCreatePayload{
		Token:     created.Token,
		URL:       url,
		ExpiresAt: created.ExpiresAt,
	}, nil
}

// RevokeShare is the resolver for the revokeShare field.
func (r *mutationResolver) RevokeShare(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeShare - revokeShare"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Extract user from context (AuthMiddleware sets user id on context)
	if ctx == nil {
		return nil, nil
	}

	if v := ctx.Value("userID"); v != nil {
		if id, ok := v.(string); ok {
			var u struct {
				ID        string    `db:"id"`
				Email     string    `db:"email"`
				Role      string    `db:"role"`
				CreatedAt time.Time `db:"created_at"`
			}
			if err := r.DB.Get(&u, "SELECT id, email, role, created_at FROM users WHERE id=$1", id); err == nil {
				return &model.User{
					ID:        u.ID,
					Email:     u.Email,
					Role:      u.Role,
					CreatedAt: u.CreatedAt,
				}, nil
			}
		}
	}
	return nil, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, userFileID string) (*model.UserFile, error) {
	panic(fmt.Errorf("not implemented: File - file"))
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.StorageStats, error) {
	// Ensure user is admin
	userID, _ := ctx.Value("userID").(string)
	if userID == "" {
		return nil, fmt.Errorf("unauthenticated")
	}

	var role string
	err := r.DB.Get(&role, "SELECT role FROM users WHERE id=$1", userID)
	if err != nil || role != "admin" {
		return nil, fmt.Errorf("forbidden")
	}

	// Calculate storage statistics
	var totalDedupedBytes int64
	var originalBytes int64

	// Get total unique file storage (deduplicated)
	err = r.DB.Get(&totalDedupedBytes, "SELECT COALESCE(SUM(size_bytes), 0) FROM file_objects")
	if err != nil {
		return nil, err
	}

	// Get total original file sizes (if no deduplication)
	err = r.DB.Get(&originalBytes, `
		SELECT COALESCE(SUM(fo.size_bytes * fo.ref_count), 0) 
		FROM file_objects fo`)
	if err != nil {
		return nil, err
	}

	savedBytes := originalBytes - totalDedupedBytes
	savedPercent := float64(0)
	if originalBytes > 0 {
		savedPercent = (float64(savedBytes) / float64(originalBytes)) * 100
	}

	return &model.StorageStats{
		TotalDedupedBytes: int(totalDedupedBytes),
		OriginalBytes:     int(originalBytes),
		SavedBytes:        int(savedBytes),
		SavedPercent:      savedPercent,
	}, nil
}

// ShareByToken is the resolver for the shareByToken field.
func (r *queryResolver) ShareByToken(ctx context.Context, token string) (*model.Share, error) {
	panic(fmt.Errorf("not implemented: ShareByToken - shareByToken"))
}

// ListShares is the resolver for the listShares field.
func (r *queryResolver) ListShares(ctx context.Context, limit *int, offset *int) ([]*model.Share, error) {
	panic(fmt.Errorf("not implemented: ListShares - listShares"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
