package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/rishit911/file_vault_proj-backend/graph/generated"
	"github.com/rishit911/file_vault_proj-backend/graph/model"
	"github.com/rishit911/file_vault_proj-backend/internal/auth"
	"github.com/rishit911/file_vault_proj-backend/internal/crypto"
	"github.com/rishit911/file_vault_proj-backend/internal/db"
	"github.com/rishit911/file_vault_proj-backend/internal/server"
)

// Use the same userIDKey from server package
const userIDKey = server.UserIDKey

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	hashed, err := auth.HashPassword(password)
	if err != nil {
		return nil, err
	}

	id := uuid.New().String()
	_, err = r.DB.Exec(`INSERT INTO users (id, email, password_hash) VALUES ($1,$2,$3)`, id, email, hashed)
	if err != nil {
		return nil, err
	}

	token, err := auth.GenerateJWT(id, 24*time.Hour)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        id,
			Email:     email,
			Role:      "user",
			CreatedAt: time.Now(),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	var id, pwHash string
	if err := r.DB.QueryRowx(`SELECT id, password_hash FROM users WHERE email=$1`, email).Scan(&id, &pwHash); err != nil {
		return nil, err
	}

	if err := auth.CompareHashAndPassword(pwHash, password); err != nil {
		return nil, err
	}

	token, err := auth.GenerateJWT(id, 24*time.Hour)
	if err != nil {
		return nil, err
	}

	var createdAt time.Time
	_ = r.DB.Get(&createdAt, "SELECT created_at FROM users WHERE id=$1", id)

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        id,
			Email:     email,
			Role:      "user",
			CreatedAt: createdAt,
		},
	}, nil
}

// RegisterFile is the resolver for the registerFile field.
func (r *mutationResolver) RegisterFile(ctx context.Context, input model.RegisterFileInput) (*model.RegisterFilePayload, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	// dedup check
	var foID string
	err := r.DB.Get(&foID, "SELECT id FROM file_objects WHERE hash=$1", input.Hash)
	if err != nil || foID == "" {
		// create file_object (we'll store storage_path placeholder)
		id := uuid.New().String()
		storagePath := "/data/files/" + input.Hash
		_, err := r.DB.Exec("INSERT INTO file_objects (id, hash, storage_path, size_bytes, mime_type, ref_count) VALUES ($1,$2,$3,$4,$5,1)",
			id, input.Hash, storagePath, input.SizeBytes, input.MimeType)
		if err != nil {
			return nil, fmt.Errorf("failed to create file object: %v", err)
		}
		foID = id
	} else {
		// increment ref
		_, err = r.DB.Exec("UPDATE file_objects SET ref_count = ref_count + 1 WHERE id=$1", foID)
		if err != nil {
			return nil, fmt.Errorf("failed to increment ref count: %v", err)
		}
	}

	// create user_file
	userFileID := uuid.New().String()
	_, err = r.DB.Exec("INSERT INTO user_files (id, user_id, file_object_id, filename) VALUES ($1,$2,$3,$4)",
		userFileID, userID, foID, input.Filename)
	if err != nil {
		return nil, fmt.Errorf("failed to create user file: %v", err)
	}

	// fetch created rows to return
	var fo struct {
		ID          string    `db:"id"`
		Hash        string    `db:"hash"`
		StoragePath string    `db:"storage_path"`
		SizeBytes   int64     `db:"size_bytes"`
		MimeType    *string   `db:"mime_type"`
		RefCount    int       `db:"ref_count"`
		CreatedAt   time.Time `db:"created_at"`
	}
	err = r.DB.Get(&fo, "SELECT id, hash, storage_path, size_bytes, mime_type, ref_count, created_at FROM file_objects WHERE id=$1", foID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch file object: %v", err)
	}

	var uf struct {
		ID         string    `db:"id"`
		Filename   string    `db:"filename"`
		UploadedAt time.Time `db:"uploaded_at"`
		Visibility string    `db:"visibility"`
	}
	err = r.DB.Get(&uf, "SELECT id, filename, uploaded_at, visibility FROM user_files WHERE id=$1", userFileID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user file: %v", err)
	}

	return &model.RegisterFilePayload{
		FileObject: &model.FileObject{
			ID:          fo.ID,
			Hash:        fo.Hash,
			StoragePath: fo.StoragePath,
			SizeBytes:   int(fo.SizeBytes),
			MimeType:    fo.MimeType,
			RefCount:    fo.RefCount,
			CreatedAt:   fo.CreatedAt,
		},
		UserFile: &model.UserFile{
			ID:   uf.ID,
			User: &model.User{ID: userID},
			FileObject: &model.FileObject{
				ID:          fo.ID,
				Hash:        fo.Hash,
				StoragePath: fo.StoragePath,
				SizeBytes:   int(fo.SizeBytes),
				MimeType:    fo.MimeType,
				RefCount:    fo.RefCount,
				CreatedAt:   fo.CreatedAt,
			},
			Filename:   uf.Filename,
			Visibility: uf.Visibility,
			UploadedAt: uf.UploadedAt,
		},
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, userFileID string) (*model.DeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// CreateShare is the resolver for the createShare field.
func (r *mutationResolver) CreateShare(ctx context.Context, input model.ShareCreateInput) (*model.ShareCreatePayload, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	var fileObjectID *string
	
	// validate ownership if fileId provided and convert user_files.id to file_objects.id
	if input.FileID != nil {
		// Check ownership using user_files.id
		ownerID, err := db.GetFileOwnerID(ctx, r.DB.DB, *input.FileID)
		if err != nil {
			return nil, fmt.Errorf("file not found or access denied: %v", err)
		}
		if ownerID != userID {
			return nil, fmt.Errorf("only uploader can share")
		}
		
		// Convert user_files.id to file_objects.id for the shares table
		fileObjID, err := db.GetFileObjectID(ctx, r.DB.DB, *input.FileID)
		if err != nil {
			return nil, fmt.Errorf("failed to get file object ID: %v", err)
		}
		fileObjectID = &fileObjID
	}

	// generate token
	token, err := crypto.GenerateShareToken(18)
	if err != nil {
		return nil, err
	}

	publicVal := true
	if input.Public != nil {
		publicVal = *input.Public
	}

	share := db.Share{
		FileID:       fileObjectID,  // Use file_objects.id instead of user_files.id
		FolderID:     input.FolderID,
		OwnerID:      userID,
		Token:        token,
		Public:       publicVal,
		ExpiresAt:    input.ExpiresAt,
		MaxDownloads: input.MaxDownloads,
	}

	created, err := db.CreateShare(ctx, r.DB.DB, share)
	if err != nil {
		return nil, err
	}

	baseURL := os.Getenv("BASE_URL")
	if baseURL == "" {
		baseURL = "http://localhost:8080"
	}
	url := strings.TrimRight(baseURL, "/") + "/s/" + created.Token

	return &model.ShareCreatePayload{
		Token:     created.Token,
		URL:       url,
		ExpiresAt: created.ExpiresAt,
	}, nil
}

// RevokeShare is the resolver for the revokeShare field.
func (r *mutationResolver) RevokeShare(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeShare - revokeShare"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Extract user from context (AuthMiddleware sets user id on context)
	if ctx == nil {
		return nil, nil
	}

	if v := ctx.Value(userIDKey); v != nil {
		if id, ok := v.(string); ok {
			var u struct {
				ID        string    `db:"id"`
				Email     string    `db:"email"`
				Role      string    `db:"role"`
				CreatedAt time.Time `db:"created_at"`
			}
			if err := r.DB.Get(&u, "SELECT id, email, role, created_at FROM users WHERE id=$1", id); err != nil {
				return nil, fmt.Errorf("database query failed: %v", err)
			}
			return &model.User{
				ID:        u.ID,
				Email:     u.Email,
				Role:      u.Role,
				CreatedAt: u.CreatedAt,
			}, nil
		}
	}
	return nil, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, userFileID string) (*model.UserFile, error) {
	panic(fmt.Errorf("not implemented: File - file"))
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, filter *model.FileFilter, pagination *model.PaginationInput) (*model.FilePage, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return &model.FilePage{Items: []*model.UserFile{}, TotalCount: 0}, nil
			}
		}
	}
	userID := userIDVal.(string)

	limit := 20
	offset := 0
	if pagination != nil {
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
		if pagination.Offset != nil {
			offset = int(*pagination.Offset)
		}
	}

	// First get total count (simpler query)
	countArgs := []interface{}{userID}
	countSql := `SELECT COUNT(1) FROM user_files uf JOIN file_objects fo ON uf.file_object_id=fo.id WHERE uf.user_id=$1` + buildFilterSQL(filter, &countArgs)
	var total int
	err := r.DB.Get(&total, countSql, countArgs...)
	if err != nil {
		return nil, fmt.Errorf("count query failed: %v", err)
	}

	// If no files, return empty result
	if total == 0 {
		return &model.FilePage{Items: []*model.UserFile{}, TotalCount: 0}, nil
	}

	// Build main query with proper parameter indexing
	args := []interface{}{userID}
	sql := `SELECT
		uf.id,
		uf.filename,
		uf.uploaded_at,
		uf.visibility,
		fo.id,
		fo.hash,
		fo.storage_path,
		fo.size_bytes,
		fo.mime_type,
		fo.ref_count,
		fo.created_at
	FROM user_files uf
	JOIN file_objects fo ON uf.file_object_id = fo.id
	WHERE uf.user_id = $1`

	// Apply filters
	sql += buildFilterSQL(filter, &args)

	// Add pagination
	sql += fmt.Sprintf(" ORDER BY uf.uploaded_at DESC LIMIT $%d OFFSET $%d", len(args)+1, len(args)+2)
	args = append(args, limit, offset)

	rows, err := r.DB.Queryx(sql, args...)
	if err != nil {
		return nil, fmt.Errorf("main query failed: %v", err)
	}
	defer rows.Close()

	var items []*model.UserFile
	for rows.Next() {
		var uf struct {
			ID         string    `db:"id"`
			Filename   string    `db:"filename"`
			UploadedAt time.Time `db:"uploaded_at"`
			Visibility string    `db:"visibility"`
		}
		var fo struct {
			ID          string    `db:"id"`
			Hash        string    `db:"hash"`
			StoragePath string    `db:"storage_path"`
			SizeBytes   int64     `db:"size_bytes"`
			MimeType    *string   `db:"mime_type"`
			RefCount    int       `db:"ref_count"`
			CreatedAt   time.Time `db:"created_at"`
		}

		err := rows.Scan(
			&uf.ID, &uf.Filename, &uf.UploadedAt, &uf.Visibility,
			&fo.ID, &fo.Hash, &fo.StoragePath, &fo.SizeBytes, &fo.MimeType, &fo.RefCount, &fo.CreatedAt,
		)
		if err != nil {
			continue
		}

		userFile := &model.UserFile{
			ID:   uf.ID,
			User: &model.User{ID: userID},
			FileObject: &model.FileObject{
				ID:          fo.ID,
				Hash:        fo.Hash,
				StoragePath: fo.StoragePath,
				SizeBytes:   int(fo.SizeBytes),
				MimeType:    fo.MimeType,
				RefCount:    fo.RefCount,
				CreatedAt:   fo.CreatedAt,
			},
			Filename:   uf.Filename,
			Visibility: uf.Visibility,
			UploadedAt: uf.UploadedAt,
		}

		items = append(items, userFile)
	}

	return &model.FilePage{Items: items, TotalCount: total}, nil
}

// SearchFiles is the resolver for the searchFiles field.
func (r *queryResolver) SearchFiles(ctx context.Context, q string, filter *model.FileFilter, pagination *model.PaginationInput) (*model.FilePage, error) {
	// basic search over filename; reuse Files with filename filter
	searchFilter := &model.FileFilter{
		FilenameContains: &q,
	}

	// merge with existing filter if provided
	if filter != nil {
		if filter.MimeTypes != nil {
			searchFilter.MimeTypes = filter.MimeTypes
		}
		if filter.MinSize != nil {
			searchFilter.MinSize = filter.MinSize
		}
		if filter.MaxSize != nil {
			searchFilter.MaxSize = filter.MaxSize
		}
		if filter.DateFrom != nil {
			searchFilter.DateFrom = filter.DateFrom
		}
		if filter.DateTo != nil {
			searchFilter.DateTo = filter.DateTo
		}
		if filter.UploaderEmail != nil {
			searchFilter.UploaderEmail = filter.UploaderEmail
		}
	}

	return r.Files(ctx, searchFilter, pagination)
}

// AdminFiles is the resolver for the adminFiles field.
func (r *queryResolver) AdminFiles(ctx context.Context, pagination *model.PaginationInput) (*model.FilePage, error) {
	// Ensure user is admin
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	var role string
	err := r.DB.Get(&role, "SELECT role FROM users WHERE id=$1", userID)
	if err != nil || role != "admin" {
		return nil, fmt.Errorf("forbidden")
	}

	// fetch all user_files with pagination (limit/offset)
	limit := 50
	offset := 0
	if pagination != nil {
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
		if pagination.Offset != nil {
			offset = int(*pagination.Offset)
		}
	}

	rows, err := r.DB.Queryx(`
		SELECT 
			uf.id as user_file_id, 
			uf.filename, 
			uf.uploaded_at, 
			uf.visibility,
			fo.id as file_object_id, 
			fo.hash, 
			fo.size_bytes, 
			fo.mime_type, 
			fo.ref_count,
			fo.created_at as fo_created_at,
			u.id as user_id, 
			u.email,
			u.role,
			u.created_at as user_created_at
		FROM user_files uf
		JOIN file_objects fo ON uf.file_object_id = fo.id
		JOIN users u ON uf.user_id = u.id
		ORDER BY uf.uploaded_at DESC 
		LIMIT $1 OFFSET $2`, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []*model.UserFile
	for rows.Next() {
		var userFileID, filename, visibility string
		var uploadedAt time.Time
		var foID, foHash string
		var sizeBytes int64
		var mimeType *string
		var refCount int
		var foCreatedAt time.Time
		var uid, email, userRole string
		var userCreatedAt time.Time

		err := rows.Scan(&userFileID, &filename, &uploadedAt, &visibility, &foID, &foHash, &sizeBytes, &mimeType, &refCount, &foCreatedAt, &uid, &email, &userRole, &userCreatedAt)
		if err != nil {
			continue
		}

		user := &model.User{
			ID:        uid,
			Email:     email,
			Role:      userRole,
			CreatedAt: userCreatedAt,
		}

		fo := &model.FileObject{
			ID:        foID,
			Hash:      foHash,
			SizeBytes: int(sizeBytes),
			MimeType:  mimeType,
			RefCount:  refCount,
			CreatedAt: foCreatedAt,
		}

		uf := &model.UserFile{
			ID:         userFileID,
			Filename:   filename,
			User:       user,
			FileObject: fo,
			Visibility: visibility,
			UploadedAt: uploadedAt,
		}

		items = append(items, uf)
	}

	var total int
	_ = r.DB.Get(&total, "SELECT COUNT(1) FROM user_files")

	return &model.FilePage{Items: items, TotalCount: total}, nil
}

// AdminStats is the resolver for the adminStats field.
func (r *queryResolver) AdminStats(ctx context.Context) (*model.AdminStats, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	// Check if user is admin (you might want to implement proper admin check)
	var userRole string
	err := r.DB.Get(&userRole, "SELECT role FROM users WHERE id = $1", userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user role: %v", err)
	}
	if userRole != "admin" {
		return nil, fmt.Errorf("forbidden")
	}

	// Get admin statistics
	var totalUsers, totalFileObjects, totalUserFiles int
	var deduplicatedStorageBytes, logicalStorageBytes int64

	// Count users
	err = r.DB.Get(&totalUsers, "SELECT COUNT(*) FROM users")
	if err != nil {
		return nil, fmt.Errorf("failed to count users: %v", err)
	}

	// Count file objects (unique files)
	err = r.DB.Get(&totalFileObjects, "SELECT COUNT(*) FROM file_objects")
	if err != nil {
		return nil, fmt.Errorf("failed to count file objects: %v", err)
	}

	// Count user files (file references)
	err = r.DB.Get(&totalUserFiles, "SELECT COUNT(*) FROM user_files")
	if err != nil {
		return nil, fmt.Errorf("failed to count user files: %v", err)
	}

	// Calculate storage statistics
	err = r.DB.Get(&deduplicatedStorageBytes, "SELECT COALESCE(SUM(size_bytes), 0) FROM file_objects")
	if err != nil {
		return nil, fmt.Errorf("failed to calculate deduplicated storage: %v", err)
	}

	// Calculate logical storage (what it would be without deduplication)
	err = r.DB.Get(&logicalStorageBytes, `
		SELECT COALESCE(SUM(fo.size_bytes), 0) 
		FROM user_files uf 
		JOIN file_objects fo ON uf.file_object_id = fo.id
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to calculate logical storage: %v", err)
	}

	dedupSavingsBytes := logicalStorageBytes - deduplicatedStorageBytes

	return &model.AdminStats{
		TotalUsers:               totalUsers,
		TotalFileObjects:         totalFileObjects,
		TotalUserFiles:           totalUserFiles,
		DeduplicatedStorageBytes: int(deduplicatedStorageBytes),
		LogicalStorageBytes:      int(logicalStorageBytes),
		DedupSavingsBytes:        int(dedupSavingsBytes),
	}, nil
}

// AdminDownloads is the resolver for the adminDownloads field.
func (r *queryResolver) AdminDownloads(ctx context.Context, from *time.Time, to *time.Time, limit *int, offset *int) ([]*model.DownloadRecord, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	// Check if user is admin
	var userRole string
	err := r.DB.Get(&userRole, "SELECT role FROM users WHERE id = $1", userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user role: %v", err)
	}
	if userRole != "admin" {
		return nil, fmt.Errorf("forbidden")
	}

	// Set default pagination
	limitVal := 20
	offsetVal := 0
	if limit != nil {
		limitVal = *limit
	}
	if offset != nil {
		offsetVal = *offset
	}

	// Build query with optional date filters
	query := "SELECT id, share_id, file_id, downloader_id, ip, user_agent, created_at FROM downloads WHERE 1=1"
	args := []interface{}{}
	argIndex := 1

	if from != nil {
		query += fmt.Sprintf(" AND created_at >= $%d", argIndex)
		args = append(args, *from)
		argIndex++
	}

	if to != nil {
		query += fmt.Sprintf(" AND created_at <= $%d", argIndex)
		args = append(args, *to)
		argIndex++
	}

	query += fmt.Sprintf(" ORDER BY created_at DESC LIMIT $%d OFFSET $%d", argIndex, argIndex+1)
	args = append(args, limitVal, offsetVal)

	rows, err := r.DB.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to query downloads: %v", err)
	}
	defer rows.Close()

	var downloads []*model.DownloadRecord
	for rows.Next() {
		var download model.DownloadRecord
		var shareID, downloaderID, ip, userAgent *string
		
		err := rows.Scan(
			&download.ID,
			&shareID,
			&download.FileID,
			&downloaderID,
			&ip,
			&userAgent,
			&download.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan download record: %v", err)
		}

		download.ShareID = shareID
		download.DownloaderID = downloaderID
		download.IP = ip
		download.UserAgent = userAgent

		downloads = append(downloads, &download)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating download records: %v", err)
	}

	return downloads, nil
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.StorageStats, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	// Get user's file statistics
	var totalDeduped, original int64
	
	// Get total deduplicated storage (unique file objects for this user)
	err := r.DB.Get(&totalDeduped, `
		SELECT COALESCE(SUM(DISTINCT fo.size_bytes), 0) 
		FROM user_files uf 
		JOIN file_objects fo ON uf.file_object_id = fo.id 
		WHERE uf.user_id = $1
	`, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get deduplicated storage: %v", err)
	}

	// Get total logical storage (sum of all user files)
	err = r.DB.Get(&original, `
		SELECT COALESCE(SUM(fo.size_bytes), 0) 
		FROM user_files uf 
		JOIN file_objects fo ON uf.file_object_id = fo.id 
		WHERE uf.user_id = $1
	`, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get original storage: %v", err)
	}

	saved := original - totalDeduped
	savedPercent := float64(0)
	if original > 0 {
		savedPercent = (float64(saved) / float64(original)) * 100
	}

	return &model.StorageStats{
		TotalDedupedBytes: int(totalDeduped),
		OriginalBytes:     int(original),
		SavedBytes:        int(saved),
		SavedPercent:      savedPercent,
	}, nil
}

// ShareByToken is the resolver for the shareByToken field.
func (r *queryResolver) ShareByToken(ctx context.Context, token string) (*model.Share, error) {
	// Get share from database
	dbShare, err := db.GetShareByToken(ctx, r.DB.DB, token)
	if err != nil {
		return nil, fmt.Errorf("share not found")
	}

	// Check if share is expired
	if dbShare.ExpiresAt != nil && dbShare.ExpiresAt.Before(time.Now()) {
		return nil, fmt.Errorf("share has expired")
	}

	// Check download limits
	if dbShare.MaxDownloads != nil {
		count, err := db.CountDownloadsForShare(ctx, r.DB.DB, dbShare.ID)
		if err != nil {
			return nil, fmt.Errorf("error checking download count")
		}
		if count >= *dbShare.MaxDownloads {
			return nil, fmt.Errorf("download limit exceeded")
		}
	}

	// Convert to GraphQL model
	share := &model.Share{
		ID:           dbShare.ID,
		FileID:       dbShare.FileID,
		FolderID:     dbShare.FolderID,
		Token:        dbShare.Token,
		Public:       dbShare.Public,
		ExpiresAt:    dbShare.ExpiresAt,
		MaxDownloads: dbShare.MaxDownloads,
		CreatedAt:    dbShare.CreatedAt,
	}

	return share, nil
}

// ListShares is the resolver for the listShares field.
func (r *queryResolver) ListShares(ctx context.Context, limit *int, offset *int) ([]*model.Share, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return []*model.Share{}, nil
			}
		}
	}
	userID := userIDVal.(string)

	// Set default pagination values
	limitVal := 20
	offsetVal := 0
	if limit != nil {
		limitVal = *limit
	}
	if offset != nil {
		offsetVal = *offset
	}

	// Get shares from database
	dbShares, err := db.ListSharesByOwner(ctx, r.DB.DB, userID, limitVal, offsetVal)
	if err != nil {
		return nil, fmt.Errorf("failed to list shares: %v", err)
	}

	// Convert database shares to GraphQL model shares
	var shares []*model.Share
	for _, dbShare := range dbShares {
		share := &model.Share{
			ID:           dbShare.ID,
			FileID:       dbShare.FileID,
			FolderID:     dbShare.FolderID,
			Token:        dbShare.Token,
			Public:       dbShare.Public,
			ExpiresAt:    dbShare.ExpiresAt,
			MaxDownloads: dbShare.MaxDownloads,
			CreatedAt:    dbShare.CreatedAt,
		}
		shares = append(shares, share)
	}

	return shares, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*model.Tag, error) {
	tags, err := db.GetAllTags(ctx, r.DB)
	if err != nil {
		return nil, err
	}
	
	result := make([]*model.Tag, len(tags))
	for i, tag := range tags {
		result[i] = &model.Tag{
			ID:   tag.ID,
			Name: tag.Name,
		}
	}
	return result, nil
}

// FilesByTag is the resolver for the filesByTag field.
func (r *queryResolver) FilesByTag(ctx context.Context, tagName string, pagination *model.PaginationInput) (*model.FilePage, error) {
	limit := 20
	offset := 0
	if pagination != nil {
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
	}

	fileIDs, totalCount, err := db.GetFilesByTag(ctx, r.DB, tagName, limit, offset)
	if err != nil {
		return nil, err
	}

	// Convert file IDs to UserFile objects
	userFiles := make([]*model.UserFile, 0, len(fileIDs))
	for _, fileID := range fileIDs {
		userFile, err := r.getUserFileByID(ctx, fileID)
		if err != nil {
			continue // Skip files that can't be loaded
		}
		userFiles = append(userFiles, userFile)
	}

	return &model.FilePage{
		Items:      userFiles,
		TotalCount: totalCount,
	}, nil
}

// AddTagToFile is the resolver for the addTagToFile field.
func (r *mutationResolver) AddTagToFile(ctx context.Context, fileID string, tagName string) (bool, error) {
	err := db.AddTagToFile(ctx, r.DB, fileID, tagName)
	return err == nil, err
}

// RemoveTagFromFile is the resolver for the removeTagFromFile field.
func (r *mutationResolver) RemoveTagFromFile(ctx context.Context, fileID string, tagName string) (bool, error) {
	err := db.RemoveTagFromFile(ctx, r.DB, fileID, tagName)
	return err == nil, err
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, name string) (*model.Tag, error) {
	tag, err := db.CreateTag(ctx, r.DB, name)
	if err != nil {
		return nil, err
	}
	return &model.Tag{
		ID:   tag.ID,
		Name: tag.Name,
	}, nil
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, name string) (bool, error) {
	err := db.DeleteTag(ctx, r.DB, name)
	return err == nil, err
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input model.CreateFolderInput) (*model.Folder, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	f := db.Folder{
		Name:     input.Name,
		OwnerID:  userID,
		ParentID: input.ParentID,
	}
	created, err := db.CreateFolder(ctx, r.DB.DB, f)
	if err != nil {
		return nil, err
	}
	return &model.Folder{
		ID:        created.ID,
		Name:      created.Name,
		OwnerID:   created.OwnerID,
		ParentID:  created.ParentID,
		CreatedAt: created.CreatedAt,
	}, nil
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, folderID string, name string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: RenameFolder - renameFolder"))
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, folderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFolder - deleteFolder"))
}

// MoveFileToFolder is the resolver for the moveFileToFolder field.
func (r *mutationResolver) MoveFileToFolder(ctx context.Context, userFileID string, folderID *string) (bool, error) {
	panic(fmt.Errorf("not implemented: MoveFileToFolder - moveFileToFolder"))
}

// ShareFolder is the resolver for the shareFolder field.
func (r *mutationResolver) ShareFolder(ctx context.Context, folderID string, public *bool, expiresAt *time.Time, maxDownloads *int) (*model.ShareCreatePayload, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	// Verify folder ownership
	folder, err := db.GetFolder(ctx, r.DB.DB, folderID)
	if err != nil {
		return nil, fmt.Errorf("folder not found")
	}
	if folder.OwnerID != userID {
		return nil, fmt.Errorf("only folder owner can share")
	}

	token, err := crypto.GenerateShareToken(18)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token")
	}

	publicVal := true
	if public != nil {
		publicVal = *public
	}

	share := db.Share{
		FileID:       nil,
		FolderID:     &folderID,
		OwnerID:      userID,
		Token:        token,
		Public:       publicVal,
		ExpiresAt:    expiresAt,
		MaxDownloads: maxDownloads,
	}

	created, err := db.CreateShare(ctx, r.DB.DB, share)
	if err != nil {
		return nil, fmt.Errorf("failed to create share")
	}

	baseURL := "http://localhost:8080" // TODO: make configurable
	url := baseURL + "/s/" + created.Token
	return &model.ShareCreatePayload{
		Token:     created.Token,
		URL:       url,
		ExpiresAt: created.ExpiresAt,
	}, nil
}

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(ctx context.Context, id string) (*model.Folder, error) {
	folder, err := db.GetFolder(ctx, r.DB.DB, id)
	if err != nil {
		return nil, err
	}
	return &model.Folder{
		ID:        folder.ID,
		Name:      folder.Name,
		OwnerID:   folder.OwnerID,
		ParentID:  folder.ParentID,
		CreatedAt: folder.CreatedAt,
	}, nil
}

// MyFolders is the resolver for the myFolders field.
func (r *queryResolver) MyFolders(ctx context.Context, limit *int, offset *int) ([]*model.Folder, error) {
	userIDVal := ctx.Value(userIDKey)
	if userIDVal == nil {
		// Debug: try different context keys
		if v := ctx.Value("userID"); v != nil {
			userIDVal = v
		} else {
			// Try the server.UserIDKey directly
			if v := ctx.Value(server.UserIDKey); v != nil {
				userIDVal = v
			} else {
				return nil, fmt.Errorf("unauthenticated - no user context found")
			}
		}
	}
	userID := userIDVal.(string)

	limitVal := 50
	offsetVal := 0
	if limit != nil {
		limitVal = *limit
	}
	if offset != nil {
		offsetVal = *offset
	}

	folders, err := db.ListUserFolders(ctx, r.DB.DB, userID, limitVal, offsetVal)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Folder, len(folders))
	for i, folder := range folders {
		result[i] = &model.Folder{
			ID:        folder.ID,
			Name:      folder.Name,
			OwnerID:   folder.OwnerID,
			ParentID:  folder.ParentID,
			CreatedAt: folder.CreatedAt,
		}
	}
	return result, nil
}

// getTagsForUserFile is a helper function to get tags for a user file
func (r *Resolver) getTagsForUserFile(ctx context.Context, fileObjectID string) ([]*model.Tag, error) {
	tags, err := db.GetTagsForFile(ctx, r.DB, fileObjectID)
	if err != nil {
		return nil, err
	}
	
	result := make([]*model.Tag, len(tags))
	for i, tag := range tags {
		result[i] = &model.Tag{
			ID:   tag.ID,
			Name: tag.Name,
		}
	}
	return result, nil
}

// getUserFileByID is a helper function to get a UserFile by ID
func (r *Resolver) getUserFileByID(ctx context.Context, userFileID string) (*model.UserFile, error) {
	type userFileRow struct {
		UserFileID   string `db:"user_file_id"`
		UserID       string `db:"user_id"`
		UserEmail    string `db:"user_email"`
		FileObjectID string `db:"file_object_id"`
		Filename     string `db:"filename"`
		Visibility   string `db:"visibility"`
		UploadedAt   string `db:"uploaded_at"`
		Hash         string `db:"hash"`
		StoragePath  string `db:"storage_path"`
		SizeBytes    int64  `db:"size_bytes"`
		MimeType     string `db:"mime_type"`
		RefCount     int    `db:"ref_count"`
		CreatedAt    string `db:"created_at"`
	}
	
	var row userFileRow
	query := `
		SELECT 
			uf.id as user_file_id,
			uf.user_id,
			u.email as user_email,
			uf.file_object_id,
			uf.filename,
			COALESCE(uf.visibility, 'private') as visibility,
			uf.uploaded_at,
			fo.hash,
			fo.storage_path,
			fo.size_bytes,
			fo.mime_type,
			fo.ref_count,
			fo.created_at
		FROM user_files uf
		JOIN users u ON uf.user_id = u.id
		JOIN file_objects fo ON uf.file_object_id = fo.id
		WHERE uf.id = $1`
	
	err := r.DB.GetContext(ctx, &row, query, userFileID)
	if err != nil {
		return nil, err
	}
	
	// Parse timestamps
	uploadedAt, _ := time.Parse(time.RFC3339, row.UploadedAt)
	createdAt, _ := time.Parse(time.RFC3339, row.CreatedAt)
	
	return &model.UserFile{
		ID: row.UserFileID,
		User: &model.User{
			ID:    row.UserID,
			Email: row.UserEmail,
			Role:  "user", // Default role
		},
		FileObject: &model.FileObject{
			ID:          row.FileObjectID,
			Hash:        row.Hash,
			StoragePath: row.StoragePath,
			SizeBytes:   int(row.SizeBytes),
			MimeType:    &row.MimeType,
			RefCount:    row.RefCount,
			CreatedAt:   createdAt,
		},
		Filename:   row.Filename,
		Visibility: row.Visibility,
		UploadedAt: uploadedAt,
	}, nil
}



// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
