name: CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install deps
        run: cd backend && go mod download
      - name: Run go vet & fmt
        run: cd backend && go vet ./... && gofmt -l .
      - name: Build
        run: cd backend && go build ./...
      - name: Run tests
        run: cd backend && go test ./...

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install & Build
        run: cd frontend && npm ci && npm run build